# Generated by Django 2.0 on 2022-04-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_numbre',
            new_name='phone_number',
        ),
    ]
